# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled0.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1e_JNNvhKANWDzswK0TG3EABONZihVj
"""

u = "5, 6, 18, 2, 7";
print(hash(u));





h = 5000;
day = h//24;
hour = h%24;
print(day, "дней", hour, "часов");

list_cities = [
    "Москва", 
    "Санкт-Петербург", 
    "Ижевск", 
    "Владивосток", 
    "Новосибирск"
];
print(list_cities[0:3]);

list_cities = [
    "Санкт-Петербург", "Москва", "Сызрань",  
    "Санкт-Петербург", "Санкт-Петербург", "Сызрань", 
] ;
print(set(list_cities));

dict_cities = {'Москва': 1, 'Сызрань': 2, 'Санкт-Петербург': 4};

print(dict_cities['Москва']);